### ISSUE TITLE
Fix use of fixtures in tests after go 1.15

### ISSUE THREAD

**Issue by ggalmazor** [dnsimple/dnsimple-go#104]
Go 1.15 drops support for `Transfer-Encoding: identity` on `net/http`, and all our fixtures use it, which is currently breaking the build.

We have discussed the following options:
- Find workarounds to the new restriction
  - Try not to declare a `Transfer-Encoding` (the module source hints that `identity` is inferred in that case) in case we can trick the module to use the fixtures
  - This could have an unintended effect of breaking builds of other clients that are not prepared to work with fixtures that don't have a `Transfer-Encoding` header.
- Change all fixtures to `Transfer-Encoding: chunked` (for reference: https://github.com/dnsimple/dnsimple-developer/pull/250)
  - This could have an unintended effect of breaking builds of other clients that are not prepared to work with chunked fixtures. 
- Change the way current fixtures are used in tests so that their contents are plugged into blank HTTP responses as we do in some other DNSimple clients
  - This could require some work but ultimately looks like the most contained approach
- Change the testing strategy to avoid having to use fixtures
  - This would deviate from how we test other clients in a way that would make it impossible to apply in an isolated way to just this client

**Comment by ggalmazor** [comment]
Pinging @DXTimer, @OleMchls, @duduribeiro in case they can add more insights/ideas to the ticket's description

**Comment by OleMchls** [comment]
I'm voting to remove the `Transfer-Encoding` alltogether as it's not required by the protocol

**Comment by duduribeiro** [comment]
I vote to drop `Transfer-Encoding` as well.

**Comment by ggalmazor** [comment]
Just to be clear: dropping the `Transfer-Encoding` needs to yet be tested because we have not verified that it will actually solve the issue. Making this change will also involve testing it in all the other clients because they could be not prepared for that.

**Comment by duduribeiro** [comment]
It is working now. We can see it on https://github.com/dnsimple/dnsimple-go/pull/103
