### ISSUE TITLE
Zones.ListRecords should accept zoneName not zoneID

### ISSUE THREAD

**Issue by fastest963** [dnsimple/dnsimple-go#23]
If you try and send `zoneID` to `Zones.ListRecords` then it 404's but if you send the `zoneName` then it works correctly. The docs indicate that it should be the name of the zone too: https://developer.dnsimple.com/v2/zones/records/#list

**Comment by weppos** [comment]
It's correct. The numeric identifier is not supported for querying. You should only use the `zoneName`. The numeric `ID` is not really used anywhere in the API. We were also considering to not output it in the API.

Do you have any suggestion to make it less confusing?
