### ISSUE TITLE
Missing Vanity Name Server struct 

### ISSUE THREAD

**Issue by jacegu** [dnsimple/dnsimple-go#44]
The Vanity Name Server related registrar endpoint [`delegateToVanity`](https://developer.dnsimple.com/v2/registrar/delegation/#delegateToVanity) returns a complex [response](https://github.com/dnsimple/dnsimple-developer/blob/master/fixtures/v2/changeDomainDelegationToVanity/success.http) which is a list of hashes. However the client has no struct for that data and we simply return a list of maps.

Aren't we missing a struct that represents a Vanity Name Server?

**Comment by weppos** [comment]
Closed in https://github.com/dnsimple/dnsimple-go/commit/21707bb655bd955a43a38b1fece7b61c9ff99c07
