### ISSUE TITLE
Expose specific model errors on validation error

### ISSUE THREAD

**Issue by sbastn** [dnsimple/dnsimple-go#60]
We currently don't expose model-specific errors (the content of the "errors" payload) when a 400 error message is returned in case of a validation failure (e.g. on create).

It would be helpful to include these errors as well to help identifying the issue.
https://github.com/dnsimple/dnsimple-go/blob/2419a4c846d40f8909f6faaac6e81cfd7655aebd/dnsimple/dnsimple.go#L276-L281

**Comment by randallmlough** [comment]
+1
It took me an unhealthy amount of time to figure out I had to put a "+" symbol in the phone number / fax string to create a contact. Documentation doesn't even mention this as a requirement.

**Comment by weppos** [comment]
Sorry about that @randallmlough. We'll see if we can prioritize the work. Feel free to provide a PR if you have something ready.

**Comment by weppos** [comment]
Related to https://github.com/dnsimple/dnsimple-developer/issues/133
