### ISSUE TITLE
go get from within dnsimple-go root directory errors

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-go#62]
If I run `go get` inside a fresh checkout of this repository, I receive an error as follows:

> can't load package: package github.com/dnsimple/dnsimple-go: no Go files in ...

To run `go get` I have to `cd dnsimple` and then run `go get`.

**Comment by weppos** [comment]
That's expected, because the real package is inside the `/dnsimple/` folder. It should be in the README to cd to `/dnsimple`.

**Comment by weppos** [comment]
Actually, why did you run `go get`?

You generally run it (as per the README) passing a proper package:

    $ go get github.com/dnsimple/dnsimple-go/dnsimple

**Comment by aeden** [comment]
Because I'm not running it as if I'm installing, I'm running as if I'm contributing. I want the dependencies of the dnsimple-go library, not dnsimple-go as a dependency.
