### ISSUE TITLE
Zones.ListRecords ignores ZoneRecordListOptions.Type

### ISSUE THREAD

**Issue by tjcelaya** [dnsimple/dnsimple-go#65]
The `Type` field in `ZoneRecordListOptions` seems to be ignored by the API though `Name` and `NameLike` both seem to work. I'm assuming this is a holdover from API v1, in which case the field should be removed now that v1 is being discontinued. The addition of `record_type` filtering in v2 would be nice though!

**Comment by weppos** [comment]
`type` is an accepted filter:
https://developer.dnsimple.com/v2/zones/records/#list

I am investigating the report right now.

**Comment by weppos** [comment]
I was able to reproduce the issue, it looks like `ZoneRecordListOptions` serializes the option as `record_type` while it should be `type`. I'm fixing it.
