### ISSUE TITLE
DNSSEC rotation webhook

### ISSUE THREAD

**Issue by arnested** [dnsimple/dnsimple-go#74]
I don't see an implementation for `dnssec.rotation_start` and `dnssec.rotation_complete` webhook events. 

And I can't find documentation on how the data for these events look either (making it difficult to do a PR).

Any hints or pointers?

**Comment by weppos** [comment]
You are right, some events are not defined as specific structs (yet).

I am going to collect the payload for a dnssec event and update the lib. I also think that we should probably generate fixtures for events as well, like we do for the other HTTP calls.
https://github.com/dnsimple/dnsimple-developer/tree/master/fixtures/v2

Thanks for the feedback.

**Comment by weppos** [comment]
Sorry for the delay @arnested , fixtures have been merged into this repo and also published in our developer site.

**Comment by arnested** [comment]
And thank you, @weppos. I finally git around to using it: https://github.com/reload/dnsimple-dk-hostmaster-ds-upload :-)

**Comment by weppos** [comment]
Thanks @arnested for the reference. It's a great use case for the webhook :)
