### ISSUE TITLE
Blank Name in query options on Zones.ListRecords skips name filtering

### ISSUE THREAD

**Issue by aeden** [dnsimple/dnsimple-go#88]
When listing zone records and setting the Name field to "", all records of the given type are returned since the Name field will be omitted from the query.

**Comment by weppos** [comment]
Similar to https://github.com/dnsimple/dnsimple-go/issues/33. Same problem, in Go you can't distinguish between an empty string and an omitted string. Unless you pass pointers to strings.

**Comment by ggalmazor** [comment]
Hi! This issue is tagged `triage` but I'm not sure how to deal with it according to the triaging guide. Should we remove the tag?

**Comment by weppos** [comment]
While investigating this bug I found more issues connected with Go zero-values. For instance, in the pagination settings, if you create a `ListOptions{Page: 5}`, it will by default also send a `PerPage` value of 0.
